version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
      - npm install --prefix frontend
  build:
    commands:
      - npm run build --prefix frontend
artifacts:
  files:
    - 'backend/**/*'
    - 'frontend/build/**/*'
    - 'package.json'
    - 'frontend/package.json'