version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - cd frontend && npm install
      - cd ../backend && npm install
  build:
    commands:
      - echo Building frontend...
      - cd ../frontend && npm run build
  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'
  discard-paths: no
