version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - (cd frontend && npm install)
      - (cd backend && npm install)
  build:
    commands:
      - echo Building frontend...
      - (cd frontend && npm run build)
      - echo Copying frontend build to backend...
      - cp -a frontend/build backend/build
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - backend/**/*
    - package.json
